# Generated by Django 2.0.3 on 2019-11-26 11:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secret_code', models.TextField()),
                ('external_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_locationgp', to='country_api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PanelProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.IntegerField(default=0)),
                ('secret_code', models.TextField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('panel_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_panel_provider', to='country_api.PanelProvider')),
                ('parent_target', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_children', to='country_api.TargetGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='panel_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_panel_provider', to='country_api.PanelProvider'),
        ),
        migrations.AddField(
            model_name='location',
            name='group_ref',
            field=models.ManyToManyField(blank=True, related_name='location_gp', to='country_api.LocationGroup'),
        ),
        migrations.AddField(
            model_name='country',
            name='panel_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_panel_provider', to='country_api.PanelProvider'),
        ),
        migrations.AddField(
            model_name='country',
            name='target_ref',
            field=models.ManyToManyField(blank=True, related_name='target_gp', to='country_api.TargetGroup'),
        ),
    ]
